apiVersion: v1
kind: Template
labels:
  template: topological-inventory-ingress-api-build-config
metadata:
  name: topological-inventory-ingress-api-build-config
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: topological-inventory-ingress-api
  spec:
    source:
      type: Git
      git:
        uri: git://github.com/ManageIQ/topological_inventory-ingress_api
        ref: master
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: topological-inventory-ingress-api:latest
        namespace: ${IMAGE_NAMESPACE}
    triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_WEBHOOK_SECRET}
parameters:
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: Namespace to push the resulting image stream tag to
  value: buildfactory
- name: GITHUB_WEBHOOK_SECRET
  displayName: GitHub Webhook Secret
  description: Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
