apiVersion: v1
kind: Template
metadata:
  name: topological-inventory-ingress-api
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: topological-inventory-ingress-api
    labels:
      app: topological-inventory
  spec:
    ports:
    - name: topological-inventory-ingress-api
      port: 3000
      targetPort: 3000
    selector:
      name: topological-inventory-ingress-api
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: topological-inventory-ingress-api
    labels:
      app: topological-inventory
  spec:
    replicas: 1
    selector:
      name: topological-inventory-ingress-api
    template:
      metadata:
        name: topological-inventory-ingress-api
        labels:
          name: topological-inventory-ingress-api
          app: topological-inventory
      spec:
        containers:
        - name: topological-inventory-ingress-api
          image: ${IMAGE_NAMESPACE}/topological-inventory-ingress-api:latest
          ports:
          - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
          env:
          - name: DATABASE_HOST
            value: topological-inventory-postgresql
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: topological-inventory-database-secrets
                key: database-url
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: topological-inventory-api-secrets
                key: secret-key
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: topological-inventory-api-secrets
                key: encryption-key
          - name: QUEUE_HOST
            value: ${QUEUE_HOST}
          - name: QUEUE_PORT
            value: "9092"
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - topological-inventory-ingress-api
          from:
            kind: ImageStreamTag
            name: topological-inventory-ingress-api:latest
            namespace: ${IMAGE_NAMESPACE}
parameters:
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: Namespace which contains the image stream to pull from
  value: buildfactory
- name: QUEUE_HOST
  displayName: Message Queue Hostname
  description: Hostname which will be used to contact the message queue.
  required: true
