apiVersion: v1
kind: DeploymentConfig
metadata:
  name: topological-inventory-orchestrator
  labels:
    app: topological-inventory
spec:
  replicas: 1
  selector:
    name: topological-inventory-orchestrator
  template:
    metadata:
      name: topological-inventory-orchestrator
      labels:
        name: topological-inventory-orchestrator
        app: topological-inventory
    spec:
      containers:
      - name: topological-inventory-orchestrator
        image: topological-inventory-ci/topological-inventory-orchestrator:latest
        env:
        - name: API_URL
          value: http://topological-inventory-api:3000/api/v0
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: topological-inventory-database-secrets
              key: database-password
        - name: DATABASE_NAME
          value: topological_inventory_production
        - name: DATABASE_HOST
          value: topological-inventory-postgresql
        - name: DATABASE_PORT
          value: "5432"
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: topological-inventory-api-secrets
              key: encryption-key
        - name: INGRESS_API_URL
          value: http://topological-inventory-ingress-api:4567
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: topological-inventory-orchestrator
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - topological-inventory-orchestrator
        from:
          kind: ImageStreamTag
          name: topological-inventory-orchestrator:latest
