apiVersion: v1
kind: Template
labels:
  template: topological-inventory-amazon-collector-${SOURCE_ID}
metadata:
  name: topological-inventory-amazon-collector-${SOURCE_ID}
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: topological-inventory-amazon-collector-secrets-${SOURCE_ID}
    labels:
      app: topological-inventory
  stringData:
    access-key-id: ${ACCESS_KEY_ID}
    secret-access-key: ${SECRET_ACCESS_KEY}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: topological-inventory-amazon-collector-${SOURCE_ID}
    labels:
      app: topological-inventory
  spec:
    replicas: 1
    selector:
      name: topological-inventory-amazon-collector-${SOURCE_ID}
    template:
      metadata:
        name: topological-inventory-amazon-collector-${SOURCE_ID}
        labels:
          name: topological-inventory-amazon-collector-${SOURCE_ID}
          app: topological-inventory
      spec:
        containers:
        - name: topological-inventory-amazon-collector-${SOURCE_ID}
          image: ${IMAGE_NAMESPACE}/topological-inventory-amazon-collector:latest
          env:
          - name: ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: topological-inventory-amazon-collector-secrets-${SOURCE_ID}
                key: access-key-id
          - name: INGRESS_API
            value: http://${INGRESS_SERVICE_HOST}:${INGRESS_SERVICE_PORT}
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: topological-inventory-amazon-collector-secrets-${SOURCE_ID}
                key: secret-access-key
          - name: SOURCE_UID
            value: ${SOURCE_UID}
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - topological-inventory-amazon-collector-${SOURCE_ID}
          from:
            kind: ImageStreamTag
            name: topological-inventory-amazon-collector:latest
            namespace: ${IMAGE_NAMESPACE}
parameters:
- name: ACCESS_KEY_ID
  displayName: Amazon Access Key ID
  description: Amazon account access ID
  required: true
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: Namespace which contains the image stream to pull from
  value: buildfactory
- name: INGRESS_SERVICE_HOST
  displayName: Ingress Service Host
  description: Hostname of the ingress service
  required: true
  value: topological-inventory-ingress-api
- name: INGRESS_SERVICE_PORT
  displayName: Ingress Service Port
  description: Port to access on the Ingress Service Host
  required: true
  value: "3000"
- name: SECRET_ACCESS_KEY
  displayName: Amazon Access Key Secret
  description: Amazon account acces key secret
  required: true
- name: SOURCE_ID
  displayName: Source ID
  description: Source id to differentiate between different instances
  required: true
- name: SOURCE_UID
  displayName: Source UID
  description: Source to collect data from
  required: true
