apiVersion: v1
kind: Template
labels:
  template: topological-inventory-database-secrets
metadata:
  name: topological-inventory-database-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: topological-inventory-database-secrets
    labels:
      app: topological-inventory
  stringData:
    database-password: "${DATABASE_PASSWORD}"
    database-url: postgresql://root:${DATABASE_PASSWORD}@topological-inventory-postgresql:5432/topological_inventory_production?encoding=utf8&pool=5&wait_timeout=5
parameters:
- name: DATABASE_PASSWORD
  displayName: PostgreSQL Password
  required: true
  description: Password for the PostgreSQL user.
  from: "[a-zA-Z0-9]{8}"
  generate: expression
