apiVersion: v1
kind: Template
labels:
  template: topological-inventory-database-secrets
metadata:
  name: topological-inventory-database-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: topological-inventory-db
    labels:
      app: topological-inventory
  stringData:
    hostname: topological-inventory-postgresql
    password: "${DATABASE_PASSWORD}"
    username: root
parameters:
- name: DATABASE_PASSWORD
  displayName: PostgreSQL Password
  required: true
  description: Password for the PostgreSQL user.
  from: "[a-zA-Z0-9]{8}"
  generate: expression
