apiVersion: v1
kind: Template
metadata:
  name: topological-inventory-host-inventory-sync
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: topological-inventory-host-inventory-sync
    labels:
      app: topological-inventory
  spec:
    replicas: 1
    selector:
      name: topological-inventory-host-inventory-sync
    template:
      metadata:
        name: topological-inventory-host-inventory-sync
        labels:
          name: topological-inventory-host-inventory-sync
          app: topological-inventory
      spec:
        containers:
        - name: topological-inventory-host-inventory-sync
          image: ${IMAGE_NAMESPACE}/topological-inventory-host-inventory-sync:latest
          env:
          - name: APP_NAME
            value: ${APP_NAME}
          - name: HOST_INVENTORY_API
            value: ${HOST_INVENTORY_SCHEME}://${HOST_INVENTORY_HOST}:${HOST_INVENTORY_PORT}
          - name: IMAGE_NAMESPACE
            value: ${IMAGE_NAMESPACE}
          - name: PATH_PREFIX
            value: ${PATH_PREFIX}
          - name: QUEUE_HOST
            value: ${QUEUE_HOST}
          - name: QUEUE_PORT
            value: "9092"
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - topological-inventory-host-inventory-sync
          from:
            kind: ImageStreamTag
            name: topological-inventory-host-inventory-sync:latest
            namespace: ${IMAGE_NAMESPACE}
parameters:
- name: APP_NAME
  displayName: Application Name
  description: Application name to be used in request paths. Only used when PATH_PREFIX is also specified.
  value: topological-inventory
- name: HOST_INVENTORY_HOST
  displayName: Host-based Inventory Service Host
  description: Host to use for the host-based inventory service URL.
  required: true
- name: HOST_INVENTORY_PORT
  displayName: Host-based Inventory Service Port
  description: Port to use for the host-based inventory service URL.
  required: true
  value: "8080"
- name: HOST_INVENTORY_SCHEME
  displayName: Host-based Inventory Service Scheme
  description: Scheme to use for the host-based inventory service URL. Can be either http or https
  required: true
  value: http
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: Namespace which contains the image stream to pull from
  value: buildfactory
- name: PATH_PREFIX
  displayName: Path Prefix
  description: Base path for the API
- name: QUEUE_HOST
  displayName: Message Queue Hostname
  description: Hostname which will be used to contact the message queue.
  required: true
