apiVersion: v1
kind: Template
labels:
  template: topological-inventory-api-build-config
metadata:
  name: topological-inventory-api-build-config
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: topological-inventory-api
  spec:
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: topological-inventory-api:latest
        namespace: ${IMAGE_NAMESPACE}
    triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_WEBHOOK_SECRET}
parameters:
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: Namespace to push the resulting image stream tag to
  value: buildfactory
- name: GITHUB_WEBHOOK_SECRET
  displayName: GitHub Webhook Secret
  description: Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
- name: SOURCE_REPOSITORY_URL
  description: The URL of the repository with your application source code.
  displayName: Git repository URI
  required: true
  value: https://github.com/ManageIQ/topological_inventory-api
- name: SOURCE_REPOSITORY_REF
  description: Git repository branch to check out, if different from default
  displayName: Git Reference
  required: true
  value: master
