apiVersion: v1
kind: Template
labels:
  template: topological-inventory-api-build-config
metadata:
  name: topological-inventory-api-build-config
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: topological-inventory-api
  spec:
    source:
      type: Git
      git:
        uri: git://github.com/ManageIQ/topological_inventory-api
        ref: master
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: topological-inventory-api:latest
        namespace: ${IMAGE_NAMESPACE}
parameters:
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: Namespace to push the resulting image stream tag to
  value: buildfactory
